### ISSUE TITLE
H&F for global mortality

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#369]
![Image](https://github.com/user-attachments/assets/5bfecf76-5be5-4187-97d9-58b64bd06412)

The H&F is very different for mortality rates--we should look into this.

**Comment by quciet** [comment]
![Image](https://github.com/user-attachments/assets/4aaac6b6-f095-4399-b55f-48fa6bd8f49c)

Same type of issue to be investigated together.

**Comment by PardeeCenterIFs** [comment]
It looks like the problem is in the "Total" tables, Males and Females, seem to be fine.

![Image](https://github.com/user-attachments/assets/392e45aa-46d9-490e-823a-18b77d3e0964)

**Comment by quciet** [comment]
> It looks like the problem is in the "Total" tables, Males and Females, seem to be fine.
> 
> ![Image](https://github.com/user-attachments/assets/392e45aa-46d9-490e-823a-18b77d3e0964)

I went in and checked all the individual death causes, and it seems they all match up (male + female = total). Plus, I summed up all the deaths across 15 categories in 2019 and it was around 10.65 million. Do we have an IFsHist tables that directly shows the total deaths? Or are we adding all 15 categories together to show total deaths?


![Image](https://github.com/user-attachments/assets/79917c18-92ee-4ecb-be38-1b36315db259)

**Comment by PardeeCenterIFs** [comment]
Got it on the Total, Total, this is being done on the fly, building a formula on the fly, and I was not using the correct dimensions, it was mostly adding up Total plus Females for each category, but only when doing Total, Total. I have now fixed this, and the fix will be included in version 8.38.

Now the problem with negatives in AIDSDTHS I also was able to fixed, but now I have an ugly transient, and that might take a while to figure out.

**Comment by quciet** [comment]
> Got it on the Total, Total, this is being done on the fly, building a formula on the fly, and I was not using the correct dimensions, it was mostly adding up Total plus Females for each category, but only when doing Total, Total. I have now fixed this, and the fix will be included in version 8.38.
> 
> Now the problem with negatives in AIDSDTHS I also was able to fixed, but now I have an ugly transient, and that might take a while to figure out.

Good to know and thank you for fixing this quickly! Would you mind attaching a screenshot on the transient? I can also take a further look to see if it is on the dataside. Thanks!

**Comment by PardeeCenterIFs** [comment]
I don't think this is a data issue, I think it's a problem with countries with high AIDS mortality. The transient was there before my fix, only it started on the negatives.

![Image](https://github.com/user-attachments/assets/fad4a4b0-05a2-4fe5-89e8-946320d3cc8f)

**Comment by PardeeCenterIFs** [comment]
Got it, the problem was with the change in the max age in IFs from 100 to 150, the code was not computing some mortality numbers for the ages 100 to 150, and Aids wanted to make adjusments. The fix will be included in version 8.38.

![Image](https://github.com/user-attachments/assets/d3bf955c-1afe-4944-8f17-be5921e185cc)

**Comment by quciet** [comment]
> Got it, the problem was with the change in the max age in IFs from 100 to 150, the code was not computing some mortality numbers for the ages 100 to 150, and Aids wanted to make adjusments. The fix will be included in version 8.38.
> 
> ![Image](https://github.com/user-attachments/assets/d3bf955c-1afe-4944-8f17-be5921e185cc)

Thanks for fixing this, José! 

I'm reopening it because there is another transient- from historical values to our initialization. See the graph below. I do not have your code fix so you will still see some negative values. However, even with your code fix, which gets Angola to 0.017 in 2020, it is still a lot lower than the data from IHME. This happens for some other African countries too. Any thoughts? 

![Image](https://github.com/user-attachments/assets/194f279f-4530-4fd8-b449-90daf09246b8)

**Comment by PardeeCenterIFs** [comment]
That is the same issue and it's fixed.

![Image](https://github.com/user-attachments/assets/38b2fcf9-6624-4b3a-b33a-590a16068105)

**Comment by PardeeCenterIFs** [comment]
The first graph was on deaths, not death rate.
